import { expect, test } from '@playwright/test'
import { randomBytes } from 'node:crypto'

test('AI settings persistence, permissions, fallback, desktop/mobile and themes without live keys', async ({ page, browser }) => {
  if (!process.env.DATABASE_URL?.includes('schema=quick_ticket_test')) throw new Error('Requires isolated quick_ticket_test schema')
  const errors: string[] = []; const externalRequests: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('request', (r) => { if (!r.url().startsWith('http://127.0.0.1:')) externalRequests.push(r.url()) })
  await page.request.post('/api/auth/login', { data: { username: 'admin', password: process.env.SEED_ADMIN_PASSWORD } })
  await page.goto('/settings')
  await page.getByRole('link', { name: 'AI 模型设置' }).click()
  await expect(page.getByRole('heading', { name: 'AI 模型设置' })).toBeVisible()
  const name = `UI configuration check ${Date.now()}`
  const secret = randomBytes(32).toString('hex')
  const outgoingBodies: string[] = []
  page.on('request', (r) => { if (r.url().includes('/api/ai/')) outgoingBodies.push(r.postData() || '') })
  let id = ''
  try {
    await page.getByRole('button', { name: '新增 Provider' }).click()
    const dialog = page.getByRole('dialog', { name: '新增 AI Provider' })
    await dialog.getByLabel('Provider 类型').selectOption('openai-compatible')
    await dialog.getByLabel('显示名称').fill(name)
    await dialog.getByLabel('API Base URL').fill('https://example.com/v1')
    await dialog.getByLabel('默认模型', { exact: true }).fill('manual-model-name')
    await expect(dialog.getByLabel('API Key', { exact: true })).toHaveValue('')
    await page.screenshot({ path: 'test-results/ai-provider-editor-desktop.png', fullPage: true })
    await dialog.getByLabel('API Key', { exact: true }).fill(secret)
    await dialog.getByRole('button', { name: '保存配置' }).click()
    await expect(dialog).toHaveCount(0)
    const stored = await (await page.request.get('/api/ai/providers')).json()
    id = stored.providers.find((p: { name: string }) => p.name === name).id
    const row = page.locator('.ai-provider-row').filter({ hasText: name })
    await expect(row).toContainText('********'); await expect(row.getByRole('button', { name: '测试连接' })).toBeEnabled()
    expect(JSON.stringify(stored)).not.toContain(secret); expect(outgoingBodies.join('\n')).not.toContain(secret)
    expect(outgoingBodies.some((body) => body.includes('sealedApiKey'))).toBe(true)
    await page.reload(); await expect(row).toContainText('manual-model-name')
    await page.screenshot({ path: 'test-results/ai-settings-desktop.png', fullPage: true })
    await page.getByRole('tab', { name: 'AI 功能分配' }).click()
    await expect(page.locator('.ai-feature-row')).toHaveCount(7)
    const quick = page.locator('.ai-feature-row').filter({ hasText: '快速工单语义解析' })
    await quick.getByLabel('Temperature', { exact: true }).fill('0.2')
    await quick.getByRole('button', { name: '保存 快速工单语义解析' }).click()
    await expect(quick.getByRole('status')).toContainText('已保存')
    await page.reload(); await page.getByRole('tab', { name: 'AI 功能分配' }).click()
    await expect(quick.getByLabel('Temperature', { exact: true })).toHaveValue('0.2')
    await page.getByTitle('深色', { exact: true }).click()
    await page.screenshot({ path: 'test-results/ai-features-dark.png', fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByTitle('浅色', { exact: true }).click()
    await page.screenshot({ path: 'test-results/ai-features-mobile.png', fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.getByRole('tab', { name: 'AI Providers', exact: true }).click()
    await row.getByRole('button', { name: `编辑 ${name}` }).click()
    await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('')
    await page.screenshot({ path: 'test-results/ai-provider-editor-mobile.png', fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.getByRole('button', { name: '取消', exact: true }).click()
    await page.goto('/')
    await page.getByLabel('快速工单输入').fill('浙江智享机器人 M2600无点云，张伟负责，紧急')
    await page.getByRole('button', { name: '解析并创建工单' }).click()
    await expect(page.getByRole('dialog', { name: '解析结果确认' })).toContainText('规则解析')
    await page.getByRole('button', { name: '重新编辑' }).click()
    await page.goto('/settings/ai'); await page.getByRole('tab', { name: '调用日志' }).click()
    await expect(page.locator('tbody')).toContainText('NOT_CONFIGURED')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const context = await browser.newContext({ baseURL: process.env.WEB_PORT ? `http://127.0.0.1:${process.env.WEB_PORT}` : 'http://127.0.0.1:5173' })
    await context.request.post('/api/auth/login', { data: { username: 'employee', password: process.env.SEED_EMPLOYEE_PASSWORD } })
    const employeePage = await context.newPage(); await employeePage.goto('/settings/ai'); await expect(employeePage.getByRole('alert')).toContainText('仅管理员')
    expect((await context.request.get('/api/ai/providers')).status()).toBe(403); await context.close()
    expect(errors).toEqual([]); expect(externalRequests).toEqual([])
  } finally {
    if (id) await page.request.delete(`/api/ai/providers/${id}`)
    await page.request.put('/api/ai/features/quick_ticket_parser', { data: { useSystemDefault: true, temperature: null, maxTokens: null } })
  }
})
