import { expect, test } from '@playwright/test'

test('admin completes the work item and quick work log flow', async ({ page }) => {
  if (!process.env.DATABASE_URL?.includes('schema=quick_ticket_test')) throw new Error('Requires isolated quick_ticket_test schema')
  const adminPassword = process.env.SEED_ADMIN_PASSWORD
  if (!adminPassword) throw new Error('Set SEED_ADMIN_PASSWORD for the test database before running browser tests')
  const stamp = Date.now()
  await page.goto('/')
  await page.getByLabel('账号').fill('admin')
  await page.getByLabel('密码').fill(adminPassword)
  await page.getByRole('button', { name: '安全登录' }).click()
  await expect(page.getByRole('heading', { name: /工作台/ })).toBeVisible()

  await page.getByTitle('深色').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByTitle('浅色').click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByTitle('跟随系统').click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('crm-theme'))).toBe('system')

  await page.goto('/work-items')
  await page.getByRole('button', { name: '新建工作事项' }).click()
  await page.getByLabel('标题').fill(`Playwright 教程整理 ${stamp}`)
  await page.getByLabel('工作分类').selectOption({ label: '文档资料' })
  await page.getByLabel('优先级').selectOption('HIGH')
  await page.getByRole('spinbutton', { name: '进度', exact: true }).fill('20')
  await page.getByRole('button', { name: '保存事项' }).click()
  await expect(page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` })).toBeVisible()

  const task = page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` })
  await task.click()
  await expect(page.locator('.drawer').getByRole('heading', { name: `Playwright 教程整理 ${stamp}` })).toBeVisible()
  await expect(page.locator('.drawer').getByRole('heading', { name: '关联工作记录', exact: true })).toBeVisible()
  await page.locator('.drawer').getByTitle('关闭').click()
  await page.getByTitle('看板').click()
  await expect(page.locator('.board-column')).toHaveCount(4)
  await page.getByTitle('列表').click()
  await expect(task.getByLabel(`Playwright 教程整理 ${stamp}快速进度`)).toHaveText('20%')
  await page.reload()
  await expect(page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` }).getByLabel(`Playwright 教程整理 ${stamp}快速进度`)).toHaveText('20%')
  const progress = page.getByLabel(`Playwright 教程整理 ${stamp}进度`)
  await progress.evaluate((element) => { const input = element as HTMLInputElement; Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set?.call(input, '60'); input.dispatchEvent(new Event('input', { bubbles: true })) })
  await page.waitForTimeout(50)
  await progress.dispatchEvent('pointerup')
  await expect(page.getByLabel(`Playwright 教程整理 ${stamp}快速进度`)).toHaveText('60%')
  await page.reload()
  await expect(page.getByLabel(`Playwright 教程整理 ${stamp}快速进度`)).toHaveText('60%')
  let completionMessage = ''
  page.once('dialog', async (prompt) => { completionMessage = prompt.message(); await prompt.dismiss() })
  const progressAfterReload = page.getByLabel(`Playwright 教程整理 ${stamp}进度`)
  await progressAfterReload.evaluate((element) => { const input = element as HTMLInputElement; Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set?.call(input, '100'); input.dispatchEvent(new Event('input', { bubbles: true })) })
  await page.waitForTimeout(50)
  await progressAfterReload.dispatchEvent('pointerup')
  expect(completionMessage).toContain('是否同时将状态设为“已完成”')
  await expect(page.getByLabel(`Playwright 教程整理 ${stamp}快速进度`)).toHaveText('100%')
  await page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` }).getByTitle('完成').click()
  await expect(page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` })).toContainText('已完成')
  await page.getByTitle('退出').click()
  await page.getByLabel('账号').fill('admin')
  await page.getByLabel('密码').fill(adminPassword)
  await page.getByRole('button', { name: '安全登录' }).click()
  await expect(page.getByRole('heading', { name: '今日工作台' })).toBeVisible()
  await page.goto('/work-items')
  await expect(page.locator('.task-row').filter({ hasText: `Playwright 教程整理 ${stamp}` })).toContainText('已完成')

  await page.getByRole('link', { name: '仪表盘' }).click()
  await expect(page.getByRole('heading', { name: '今日工作台' })).toBeVisible()
  await page.getByRole('link', { name: '统计报表', exact: true }).click()
  await expect(page.getByRole('heading', { name: '统计报表' })).toBeVisible()
  await expect(page.getByText('七日工作趋势')).toBeVisible()
  await page.getByRole('link', { name: '仪表盘' }).click()
  const quickText = `完成SDK教程 ${stamp}；排查M2600无点云 ${stamp}。`
  await page.goto('/worklogs?create=1')
  await page.getByPlaceholder(/上午完成SDK安装教程/).fill(quickText)
  await page.getByRole('button', { name: '生成草稿' }).click()
  await expect(page.getByLabel('记录 1')).toHaveValue(`完成SDK教程 ${stamp}`)
  await expect(page.getByLabel('记录 2')).toHaveValue(`排查M2600无点云 ${stamp}`)
  await page.getByRole('button', { name: '确认并保存' }).click()
  await expect(page.getByRole('heading', { name: '工作记录' })).toBeVisible()
  await expect(page.getByText(`完成SDK教程 ${stamp}`, { exact: true })).toBeVisible()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByTitle('导航').click()
  await expect(page.getByRole('link', { name: '我的工作', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '工作事项', exact: true })).toHaveCount(0)

  const worklogs = await (await page.request.get('/api/worklogs')).json()
  for (const worklog of worklogs.filter((item: { summary: string }) => item.summary.endsWith(String(stamp)))) {
    await page.request.delete(`/api/worklogs/${worklog.id}`)
  }
  const workItems = await (await page.request.get('/api/work-items')).json()
  for (const workItem of workItems.filter((item: { title: string }) => item.title.endsWith(String(stamp)))) {
    await page.request.delete(`/api/work-items/${workItem.id}`)
  }
})
