/** 通知类型常量（Notification.type 的单一事实源，禁止在业务代码中散落字面量） */
export const NOTIFICATION_TYPES = {
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_STATUS_CHANGED: 'TICKET_STATUS_CHANGED',
  USER_REGISTRATION: 'USER_REGISTRATION',
  LOAN_ASSIGNED: 'LOAN_ASSIGNED',
  LOAN_OVERDUE: 'LOAN_OVERDUE',
  REPAIR_ASSIGNED: 'REPAIR_ASSIGNED',
  BUG_FIXED: 'BUG_FIXED',
  TICKET_ASSIST_REQUESTED: 'TICKET_ASSIST_REQUESTED',
  TICKET_ASSIST_ACCEPTED: 'TICKET_ASSIST_ACCEPTED',
  TICKET_ASSIST_REJECTED: 'TICKET_ASSIST_REJECTED',
  TICKET_DELETED: 'TICKET_DELETED',
  TICKET_RESTORED: 'TICKET_RESTORED',
  LINK_LOAN_CREATED: 'LINK_LOAN_CREATED',
  LINK_REPAIR_CREATED: 'LINK_REPAIR_CREATED',
  LINK_LOAN_OVERDUE: 'LINK_LOAN_OVERDUE',
  LINK_ALL_COMPLETED: 'LINK_ALL_COMPLETED',
  LINK_INFO_TIMEOUT: 'LINK_INFO_TIMEOUT',
  LINK_REPAIR_NO_FOLLOWUP: 'LINK_REPAIR_NO_FOLLOWUP',
  LINK_FAILED: 'LINK_FAILED',
  TICKET_CONTINUED: 'TICKET_CONTINUED',
} as const
export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES]
